{% set version = "1.1.5" %}

package:
  name: openpisco-split
  version: {{ version }}

source:
  url: https://gitlab.com/openpisco/openpisco/-/archive/{{ version }}/openpisco-{{ version }}.tar.bz2
  sha256: 656af0662c8890fd460566211a9aefe821f0080295925435001dc6cd2617839f

build:
  number: 0

outputs:
  - name: openpisco-core
    version: {{ version }}
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - OpenPisco = OpenPisco.QtApp.OpenPiscoGUI:LaunchPiscoGUI
        - OpenPiscoCL = OpenPisco.CLApp.OpenPiscoCL:RunSimulation
      skip_compile_pyc: "OpenPiscoParaViewBridge.py"
    requirements:
      host:
        - python
        - pip
        - setuptools
      run:
        - muscat-core =2.2.2
        - eigency =3.4.0.2
        - python
        - osqp
        - numba
        - qtconsole
        - pyqtgraph
        - PySide2
        - vtk <=9.2.6
        - libmed >=4.1.1
        - qt =5
    test:
      imports:
        - OpenPisco
      commands:
        - python -m Muscat -e OpenPisco -k aster -k mmg -k meshdist -k advect -k thickness -k AMInherentStrainSolver -k Levelset -k Extension -k freefem -k zset -k qt

  - name: "openpisco"
    version: {{ version }}
    requirements:
      run:
        - openpisco-core
        - iscd-mshdist  # [not win]
        - iscd-advection  # [not win]
        - mmgsuite <=5.7.3  # [not win]
        - {{ pin_subpackage('openpisco-core', exact=True) }}
    test:
      imports:
        - OpenPisco
      commands:
        - python -m Muscat -e OpenPisco -k aster -k thickness -k AMInherentStrainSolver -k freefem -k zset -k qt -k extension  # [unix]
        - python -m Muscat -e OpenPisco -k aster -k thickness -k AMInherentStrainSolver -k freefem -k zset -k qt -k extension -k meshdist -k advect -k levelset -k mmg  # [win]


about:
  home: https://gitlab.com/openpisco/openpisco
  license_file: LICENSE
  license: LGPL-3.0-only
  license_family: LGPL
  summary: A toolbox for topology optimization
  description: |
    OpenPisco is a research and development platform devoted to topology
    optimization relying on the level set method.
  doc_url: https://openpisco.readthedocs.io/
  dev_url: https://gitlab.com/openpisco/openpisco

extra:
  recipe-maintainers:
    - fbordeu
    - cnrdn
    - daviddanan
