{% set version = "1.1.5" %}

package:
  name: openpisco-split
  version: {{ version }}

source:
  url: https://gitlab.com/openpisco/openpisco/-/archive/move-to-1.1.5/openpisco-move-to-1.1.5.tar.gz
  #sha256: 17a43f954eb5edb26760e3dacec122fb1f10f586a1990c7f83936ca143377e7d

build:
  number: 0

outputs:
  - name: openpisco-core
    version: {{ version }}
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - OpenPisco = OpenPisco.QtApp.OpenPiscoGUI:LaunchPiscoGUI
        - OpenPiscoCL = OpenPisco.CLApp.OpenPiscoCL:RunSimulation
      skip_compile_pyc:
        "OpenPiscoParaViewBridge.py"
    requirements:
      host:
        - python
        - pip
        - setuptools
      run:
        - muscat-core =2.3.0
        - eigency =3.4.0.2
        - python
        - osqp
        - numba
        - qtconsole
        - pyqtgraph
        - PySide2
        - vtk
        - qt =5
    test:
      imports:
        - OpenPisco
      commands:
        - python -m Muscat -e OpenPisco -k aster -k mmg -k meshdist -k advect -k thickness -k AMInherentStrainSolver -k Levelset -k Extension -k freefem -k zset -k qt -k med

  - name: "openpisco"
    version: {{ version }}
    requirements:
      run:
        - openpisco-core
        - iscd-mshdist  # [not win]
        - iscd-advection  # [not win]
        - mmgsuite  # [not win]
        - {{ pin_subpackage('openpisco-core', exact=True) }}
    test:
      imports:
        - OpenPisco
      commands:
        - python -m Muscat -e OpenPisco -k aster -k thickness -k freefem -k zset -k qt -k extension -k med  # [unix]
        - python -m Muscat -e OpenPisco -k aster -k thickness -k freefem -k zset -k qt -k extension -k meshdist -k AMInherentStrainSolver -k advect -k levelset -k mmg -k med  # [win]


about:
  home: https://gitlab.com/openpisco/openpisco
  license_file: LICENSE
  license: LGPL-3.0-only
  license_family: LGPL
  summary: A toolbox for topology optimization
  description: |
    OpenPisco is a research and development platform devoted to topology
    optimization relying on the level set method.
  doc_url: https://openpisco.readthedocs.io/
  dev_url: https://gitlab.com/openpisco/openpisco

extra:
  recipe-maintainers:
    - fbordeu
    - cnrdn
    - daviddanan
